version: '3.8'
services:
  # Databases
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: triumph_psql_user
      POSTGRES_PASSWORD: "_21B-N{6@Fy37D_C9&Aq"
      POSTGRES_DB: triumph_psql_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: triumph_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: 05Dr8(3X9pok]=-ON1/&
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Main Service - NestJs
  service:
    build:
      context: ./services/service
      dockerfile: Dockerfile
    container_name: service
    environment:
      DATABASE_URL: postgres://triumph_psql_user:_21B-N{6@Fy37D_C9&Aq@postgres:5432/triumph_psql_db
      MONGO_URL: mongodb://triumph_mongo_user:05Dr8(3X9pok]=-ON1/&@mongodb:27017
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - mongodb

  # Microservice Parts - Express
  parts:
    build:
      context: ./services/parts
      dockerfile: Dockerfile
    container_name: parts
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  # Microservice Essais - Express
  testdrives:
    build:
      context: ./services/testdrives
      dockerfile: Dockerfile
    container_name: testdrives
    environment:
      DATABASE_URL: postgres://triumph_psql_user:_21B-N{6@Fy37D_C9&Aq@postgres:5432/triumph_psql_db
      MONGO_URL: mongodb://triumph_mongo_user:05Dr8(3X9pok]=-ON1/&@mongodb:27017
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  # Microservice Admin - NestJs
  admin:
    build:
      context: ./services/admin
      dockerfile: Dockerfile
    container_name: admin
    environment:
      DATABASE_URL: postgres://triumph_psql_user:_21B-N{6@Fy37D_C9&Aq@postgres:5432/triumph_psql_db
      MONGO_URL: mongodb://triumph_mongo_user:05Dr8(3X9pok]=-ON1/&@mongodb:27017
    ports:
      - "3004:3004"
    depends_on:
      - postgres
      - mongodb

  # Frontend Main - React
  frontend_main:
    build:
      context: ./frontends/main
      dockerfile: Dockerfile
    container_name: frontend_main
    ports:
      - "3000:3000"

  # Frontend Admin - SolidJs
  frontend_admin:
    build:
      context: ./frontends/admin
      dockerfile: Dockerfile
    container_name: frontend_admin
    ports:
      - "3005:3005"

volumes:
  postgres_data:
  mongo_data:
